dist:
  bionic
language: cpp    
compiler: gcc
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq 
- sudo apt-get install libboost-test-dev -y   

script:
- cd part1
- cmake --version 
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uAmpermetr123:$BINTRAY_API_KEY "https://api.bintray.com/content/ampermetr123/otus-cpp/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
