dist:
  bionic
language: cpp    
compiler: gcc
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq 
- sudo apt-get install libboost-test-dev -y   

script:
- cd part1
- cmake --version 
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- cd ..

before_deploy:
  python makedeploy.py
deploy:
  provider: bintray
  file: "deploy.txt"
  user: "ampermetr123"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true # to upload artifacts created during the build
  on:
    branch: hw1

  # provider: script
  # skip_cleanup: true
  # script:
  # - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uAmpermetr123:$BINTRAY_API_KEY "https://api.bintray.com/content/ampermetr123/otus-cpp/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
  # on:
  #   branch: hw1
