dist:
  bionic
language: cpp    
compiler: gcc
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq 


script:
- cd bulk  
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE:STRING=Release
- cmake --build .

- cmake --build . --target package
- cd ../


before_deploy:
  python makedeploy.py

deploy:
  - provider: bintray
    file: "deploy.txt"
    user: "ampermetr123"
    key: "$BINTRAY_API_KEY"
    skip_cleanup: true # to upload artifacts created during the build
    on:
      branch: hw6

